// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: service_basic_bank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_basic_bank_proto protoreflect.FileDescriptor

const file_service_basic_bank_proto_rawDesc = "" +
	"\n" +
	"\x18service_basic_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_update_user.proto\x1a\x14rpc_login_user.proto\x1a\x16rpc_verify_email.proto\x1a\x18rpc_create_account.proto\x1a\x15rpc_get_account.proto\x1a\x17rpc_list_accounts.proto\x1a\x19rpc_create_transfer.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xd5\f\n" +
	"\tBasicBank\x12\x94\x02\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\xd6\x01\x92A\xb8\x01\n" +
	"\x05Users\x12\vCreate User\x1aYCreate a new user account with username, email, and password. No authentication required.J\"\n" +
	"\x03200\x12\x1b\n" +
	"\x19User created successfullyJ#\n" +
	"\x03400\x12\x1c\n" +
	"\x1aInvalid request parameters\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\xbc\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x81\x01\x92Ae\n" +
	"\x05Users\x12\n" +
	"Login User\x1a5Authenticate user and receive access & refresh tokensJ\x19\n" +
	"\x03200\x12\x12\n" +
	"\x10Login successful\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12\xaf\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"r\x92AU\n" +
	"\x05Users\x12\vUpdate User\x1a1Update user information. Requires authentication.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12\xa5\x01\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"e\x92AJ\n" +
	"\x05Users\x12\fVerify Email\x1a3Verify user's email address using verification code\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_email\x12\xd6\x01\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\"\x8f\x01\x92Au\n" +
	"\bAccounts\x12\x0eCreate Account\x1aKCreate a new bank account with specified currency. Requires authentication.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/accounts\x12\xb9\x01\n" +
	"\n" +
	"GetAccount\x12\x15.pb.GetAccountRequest\x1a\x16.pb.GetAccountResponse\"|\x92A`\n" +
	"\bAccounts\x12\vGet Account\x1a9Get account details by ID. Only account owner can access.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/accounts/{id}\x12\xa7\x01\n" +
	"\fListAccounts\x12\x17.pb.ListAccountsRequest\x1a\x18.pb.ListAccountsResponse\"d\x92AM\n" +
	"\bAccounts\x12\rList Accounts\x1a$List user's accounts with paginationb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/accounts\x12\xd8\x01\n" +
	"\x0eCreateTransfer\x12\x19.pb.CreateTransferRequest\x1a\x1a.pb.CreateTransferResponse\"\x8e\x01\x92As\n" +
	"\tTransfers\x12\x0fCreate Transfer\x1aGTransfer money between accounts. Both accounts must have same currency.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/transfersB\xb4\x03\x92A\x8a\x03\x12\xa9\x01\n" +
	"\x0eBasic Bank API\x12GA comprehensive banking API for managing users, accounts, and transfers\"I\n" +
	"\amikhail\x12$github.com/AtoyanMikhail/bank_api/pb\x1a\x18mikhail.atoyan@gmail.com2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonZ<\n" +
	":\n" +
	"\x06Bearer\x120\b\x02\x12\x1bBearer token authentication\x1a\rAuthorization \x02j#\n" +
	"\x05Users\x12\x1aUser management operationsj)\n" +
	"\bAccounts\x12\x1dAccount management operationsj&\n" +
	"\tTransfers\x12\x19Money transfer operationsZ$github.com/AtoyanMikhail/bank_api/pbb\x06proto3"

var file_service_basic_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),      // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),       // 1: pb.LoginUserRequest
	(*UpdateUserRequest)(nil),      // 2: pb.UpdateUserRequest
	(*VerifyEmailRequest)(nil),     // 3: pb.VerifyEmailRequest
	(*CreateAccountRequest)(nil),   // 4: pb.CreateAccountRequest
	(*GetAccountRequest)(nil),      // 5: pb.GetAccountRequest
	(*ListAccountsRequest)(nil),    // 6: pb.ListAccountsRequest
	(*CreateTransferRequest)(nil),  // 7: pb.CreateTransferRequest
	(*CreateUserResponse)(nil),     // 8: pb.CreateUserResponse
	(*LoginUserResponse)(nil),      // 9: pb.LoginUserResponse
	(*UpdateUserResponse)(nil),     // 10: pb.UpdateUserResponse
	(*VerifyEmailResponse)(nil),    // 11: pb.VerifyEmailResponse
	(*CreateAccountResponse)(nil),  // 12: pb.CreateAccountResponse
	(*GetAccountResponse)(nil),     // 13: pb.GetAccountResponse
	(*ListAccountsResponse)(nil),   // 14: pb.ListAccountsResponse
	(*CreateTransferResponse)(nil), // 15: pb.CreateTransferResponse
}
var file_service_basic_bank_proto_depIdxs = []int32{
	0,  // 0: pb.BasicBank.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.BasicBank.LoginUser:input_type -> pb.LoginUserRequest
	2,  // 2: pb.BasicBank.UpdateUser:input_type -> pb.UpdateUserRequest
	3,  // 3: pb.BasicBank.VerifyEmail:input_type -> pb.VerifyEmailRequest
	4,  // 4: pb.BasicBank.CreateAccount:input_type -> pb.CreateAccountRequest
	5,  // 5: pb.BasicBank.GetAccount:input_type -> pb.GetAccountRequest
	6,  // 6: pb.BasicBank.ListAccounts:input_type -> pb.ListAccountsRequest
	7,  // 7: pb.BasicBank.CreateTransfer:input_type -> pb.CreateTransferRequest
	8,  // 8: pb.BasicBank.CreateUser:output_type -> pb.CreateUserResponse
	9,  // 9: pb.BasicBank.LoginUser:output_type -> pb.LoginUserResponse
	10, // 10: pb.BasicBank.UpdateUser:output_type -> pb.UpdateUserResponse
	11, // 11: pb.BasicBank.VerifyEmail:output_type -> pb.VerifyEmailResponse
	12, // 12: pb.BasicBank.CreateAccount:output_type -> pb.CreateAccountResponse
	13, // 13: pb.BasicBank.GetAccount:output_type -> pb.GetAccountResponse
	14, // 14: pb.BasicBank.ListAccounts:output_type -> pb.ListAccountsResponse
	15, // 15: pb.BasicBank.CreateTransfer:output_type -> pb.CreateTransferResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_basic_bank_proto_init() }
func file_service_basic_bank_proto_init() {
	if File_service_basic_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_verify_email_proto_init()
	file_rpc_create_account_proto_init()
	file_rpc_get_account_proto_init()
	file_rpc_list_accounts_proto_init()
	file_rpc_create_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_basic_bank_proto_rawDesc), len(file_service_basic_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_basic_bank_proto_goTypes,
		DependencyIndexes: file_service_basic_bank_proto_depIdxs,
	}.Build()
	File_service_basic_bank_proto = out.File
	file_service_basic_bank_proto_goTypes = nil
	file_service_basic_bank_proto_depIdxs = nil
}
